steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/rl-build-services-dev/kube-lookout', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/rl-build-services-dev/kube-lookout']
