apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-lookout
  labels:
    app: kube-lookout
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-lookout
  strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
  template:
    metadata:
      labels:
        app: kube-lookout
    spec:
      serviceAccount: kube-lookout
      containers:
      - name: kube-lookout
        image: gcr.io/rl-build-services-dev/kube-lookout
        imagePullPolicy: Always
        env:
        - name: SLACK_TOKEN
          value: "insert token here"
        - name: GCP_REGION
          value: "us-west1"
        - name: GCP_PROJECT
          value: "rl-us-dev39"
        - name: CLUSTER_NAME
          value: "dev39-rl-us-dev39"
